### ISSUE TITLE
Version 1.1b  Do not work

### ISSUE THREAD

**Issue by AngelSeed** [MidoriKami/NoTankYou#1]
I have introduced Version 1.1b, but it doesn't work.
Is it not compatible with Ja?
Please let me know if there is anything.

**Comment by MidoriKami** [comment]
Can you elaborate on "but it doesn't work" ? What was your testing scenario.
Can you also clarify what "Ja" is?

**Comment by AngelSeed** [comment]
Sincerest apologies.
Ja = Japanese client.
Test content is his alliance raid, normal raid, various IDs
I went around the contents, but it didn't work well.

**Comment by MidoriKami** [comment]
Does the Settings Window appear when clicking the gear icon in the Plugin Manager?
Does the Settings Window appear upon typing /notankconfig ingame?

**Comment by AngelSeed** [comment]
Yes! Settings etc. will open. but
No notification was given when the tank stance was OFF.

**Comment by MidoriKami** [comment]
In the settings if you check "force show banner" or use the command "/notankconfig force", does the banner display anywhere?

Additionaly what version of xivquicklauncher do you use?

**Comment by AngelSeed** [comment]
It will be displayed.
xivquicklaunche v6.0.17.0
https://gyazo.com/1775ed11112df3edf4495c2727e8fe04
https://gyazo.com/cd5d56a2ce954efea4d3acf94d70d869

**Comment by MidoriKami** [comment]
If you disable clickthrough you should be able to move the warning window around.

It shouldn't show in alliance raids unless you uncheck the disable in alliance raid option. It won't display in any cross world party. Once you are in an instance your cross world party should become a normal "full party" or regular "party". It should show anytime you are in a group of 2 or more players where at least one of them are a tank.

Please test and describe a couple scenarios that you expect the warning to display, but it doesn't. I will be posting an updated version of the plugin tomorrow.

**Comment by AngelSeed** [comment]
We apologize for the inconvenience, but we are waiting for the updated version.
Thanking you in advance.

**Comment by MidoriKami** [comment]
By any chance were you a Dark Knight?

**Comment by MidoriKami** [comment]
https://github.com/MidoriKami/NoTankYou/commit/8a63d2b7f809fd625ae6d7838928ba221378f8bc
Fixes Dark Knights not being considered tanks.

**Comment by AngelSeed** [comment]
I was a warrior at that time.
I was about to give up because I couldn't confirm the operation even at present ...
