### ISSUE TITLE
[FEATURE REQUEST] Add option to not display tank warning during PvP

### ISSUE THREAD

**Issue by kgetit** [MidoriKami/NoTankYou#11]
The display warning is up during PvP mode. Currently, I would have to switch to show during duty only to have it turned off or blacklist the zones.  Please add an option to not show when in a PvP zone or instance. Thank you in advance for this awesome plugin!

**Comment by MidoriKami** [comment]
The plugin is supposed to automatically disabled in PvP zones or Golden Saucer Zones.
What version of the plugin? What is the exact name of the pvp zone?
Which modules were/are enabled? Which is showing?

**Comment by kgetit** [comment]
Job is PLD
Version 2.3.1.4
Zone: Wolf Den Pier (ID 250)
pic:
![nty](https://user-images.githubusercontent.com/93019865/149013872-26f52708-9830-4534-bc05-99f4780d085b.jpg)
Only Tank and Food modules are active.

**Comment by MidoriKami** [comment]
Wolf den pier is not a pvp zone, it's just an area. It should automatically disable once you are in an actual pvp instance.

The plugin is behaving as expected.
