### ISSUE TITLE
[Enhancement] Option to disable food check for jobs at level 90 unless in a Savage Raid.

### ISSUE THREAD

**Issue by Iaotle** [MidoriKami/NoTankYou#16]

**Comment by MidoriKami** [comment]
There is no identifier for a savage raid vs a normal raid in the databases, to do so would require manually adding each raid as they come out to the plugin. I have no intentions of modifying my plugin in any way that requires constant updating. Nor do I intend to automatically allow food checking other players for any range of dungeons by default.

I want whitelisting instances for Party-Wide food checks to be annoying, its something that I hope that people do for their statics or organize group. I do not want people harassing others for not having food on them in casual dungeons or trials.
