### ISSUE TITLE
[Bug] Food warning showing at all times, even with whitelisted areas enabled

### ISSUE THREAD

**Issue by fearkite** [MidoriKami/NoTankYou#18]
Hey mate! Thanks heaps for making this addon, it's awesome. :D

As per title, food warning is permanently showing no matter what I do - I've made sure that it isn't forced on and with whitelists available. It still shows. :(

Any ideas here?

Thanks!

**Comment by MidoriKami** [comment]
Send config

**Comment by MidoriKami** [comment]
If no additional information is provided this issue will be closed in 12 hrs.
