### ISSUE TITLE
Summoner bug

### ISSUE THREAD

**Issue by gillious82** [MidoriKami/NoTankYou#19]
Summoner Pet banner shows briefly (0.5/1s) when swapping between your summons.

**Comment by MidoriKami** [comment]
What is your fra.erate and what is your configured wait frame value?

**Comment by gillious82** [comment]
Hey, refresh rate is 165 and I've set the wait frame value to 82. I also tried the max of 144. Neither value seems to help.

**Comment by MidoriKami** [comment]
Send config

**Comment by gillious82** [comment]
https://pastebin.com/tetGcF2u

**Comment by MidoriKami** [comment]
Does it consistently show between all summons, or just occasionally?

**Comment by gillious82** [comment]
Hey, video of a friend with the same issue:- https://www.youtube.com/watch?v=zFDyt_nQRhg they are not max level so they have level 1 summons but I'm getting the exact same thing at 90. 

It seems to be between most summons but not 100% of the time.

**Comment by MidoriKami** [comment]
I'll look into a better method for managing summoner pets for the next rebuild of the plugin which won't be for several weeks, until then I will close this issue as there is no simple fix to this problem. (Blame Square Enix for making pets super jank)
