### ISSUE TITLE
Warn users when no FC Buffs are up! ❤️ 

### ISSUE THREAD

**Issue by cecilia-sanare** [MidoriKami/NoTankYou#21]
### Description

I know this is very much not something this plugin was intended for, but I figured I'd open a ticket regardless to see if there was any possibility of it being added!

Basically, just a reminder that FC Buffs are down should you have this warning active.

### Use-Case

Periodically I'll come back to the game and completely forget that the FC buffs have fallen off. 
I'll then get into a loop where I get into an instance, remember in the instance, forget once 
out of the instance, and hop back into an instance. lol

Anyways, feel free to close this ticket if you have no intentions of ever implementing something like this!~ ❤️

**Comment by MidoriKami** [comment]
That's not a bad idea. I'll need more information however as I have never dealt with fc buffs. There are two right? Would warning until at least one buff is active be sufficient?

**Comment by cecilia-sanare** [comment]
Yup! The current max is two and one would definitely be good enough!

**Comment by Jaksuhn** [comment]
> That's not a bad idea. I'll need more information however as I have never dealt with fc buffs. There are two right? Would warning until at least one buff is active be sufficient?

Two active slots available; every type of buff has three levels. Preferably, it'd be cool to pick which buff to track (as I would always want Heat of Battle to be active, and sometimes someone in the fc has another less important one active).

**Comment by MidoriKami** [comment]
Add in 56cd818ea4868c23145928e761d31f7b0b8da340

**Comment by cecilia-sanare** [comment]
Thank you so much! Also, I love the new settings menu so much! :heart:
