### ISSUE TITLE
Suggestion: Skill icons in party frame

### ISSUE THREAD

**Issue by Nillinn** [MidoriKami/NoTankYou#29]
On the party list option, instead of the orange shield on top of the job icon, the plugin could display the icon of the specific ability that is missing. It would allow the user to disable the text notification and rely on the icon alone.

Example: if a Sage didn't use Kardia, the Kardia icon will flash on top of their job icon in the party frame until they use it, replacing the current orange shield icon.

**Comment by MidoriKami** [comment]
imo it'd be too small, you wouldn't see any detail on the icon.
