### ISSUE TITLE
Detect PVP instances

### ISSUE THREAD

**Issue by iskawhiskers** [MidoriKami/NoTankYou#3]
Is there any way for NoTankYou to detect when you're in PVP instances? Since tank stances don't exist in the PVP gamemodes, NTY is constantly giving me a warning that tanks don't have their currently-unusable stances on.

**Comment by MidoriKami** [comment]
Absolutely, there is a **/notankyou blacklist** command you can use to disable NoTankYou in the instance that you use the command in. It remembers the instance via ID, so when you return at a later date, it will still be deactivated for that instance.

**Comment by MidoriKami** [comment]
Follow-up, new version of plugin automatically disables in any pvp zone.
