### ISSUE TITLE
Warning icon not displaying properly in place of Job Icon

### ISSUE THREAD

**Issue by cecilia-sanare** [MidoriKami/NoTankYou#31]
### Description

I'm guessing you already know about this, but figured I'd report it just in-case ❤️

### Steps to Reproduce

- Switch to a tank
- Have the Job Icon setting enabled on Party Frame Overlay
- Set the Tank Module to be enabled
  - Solo Mode should be enabled and duties only should be disabled (not specific to this scenario, just makes it easier to test)

### Screenshots

![image](https://user-images.githubusercontent.com/9692284/186683101-9a0327ee-b90d-4096-8460-02826c509a17.png)

**Comment by MidoriKami** [comment]
I was not aware of this issues, thanks for the report. It'll be a few days before I have time to check on this.

**Comment by MidoriKami** [comment]
Fixed in 946c034dc0cb91ed638381766a40ddb4ac4594a8
