### ISSUE TITLE
out of party list

### ISSUE THREAD

**Issue by AngelSeed** [MidoriKami/NoTankYou#32]
https://gyazo.com/48e56f3d830df7a8dbfdc13b46f634c2
Is there a way to fix the misaligned icons?

**Comment by MidoriKami** [comment]
Hmm, I'll look into, can you share your exact testing order?

**Comment by MidoriKami** [comment]
Also, do you use Dalamud Scaling or Native Game Scaling?

**Comment by AngelSeed** [comment]
I don't use Dalamud Scaling or Native Game Scaling.
I was able to do it normally until this patch 6.2.
After applying the patch and updating NoTankYou, he was like this.

**Comment by AngelSeed** [comment]
today? When Dalamud was updated and started, it returned to the original. Sorry for the inconvenience.
I will let you know if anything else happens.
thank you for always!
