### ISSUE TITLE
Can't install plugin

### ISSUE THREAD

**Issue by Enzemo** [MidoriKami/NoTankYou#34]
Hi, used to use the plugin with no problems but suddenly it stopped working yesterday.

Now it shows as uninstalled and when I try to install it I get this warning:

![image](https://user-images.githubusercontent.com/11069930/189481267-9edba5c0-bc5f-4be5-9307-f773cc925bc7.png)

**Comment by MidoriKami** [comment]
This is a dalamud plugin reposity issue not a NoTankYou issue.
The specific error is a server 404.
