### ISSUE TITLE
Feature Request: Off Tank stance

### ISSUE THREAD

**Issue by joelbartley** [MidoriKami/NoTankYou#36]
Hi, currently it seems that there is no way to get an overlay message when the off tank in 8 person content doesn't have their tank stance up. Would it be possible for you to add this as an option? Thanks!

**Comment by MidoriKami** [comment]
No, off-tanks needing their stance on is highly situational. Any system that warned when off tanks don't have their stance on would warn regardless of this situational context requiring the user to turn the feature on and off constantly.
