### ISSUE TITLE
Food warning not displaying in Minstrel's Ballad extremes

### ISSUE THREAD

**Issue by eat-a-pitta** [MidoriKami/NoTankYou#38]
As stated, the food warning doesn't appear when in Minstrel's Ballad content. I have checked all "Zone Filters" and they are all on (and work for everything else). I'm guessing that the Minstrel's Ballad fights don't actually count as extremes in the game, and that's why it isn't showing. I don't know if this is intentional or not but if it is, it would be nice to include it!
I'm not 100% sure if this is also a problem in recent Minstrel's Ballads, as I've been playing Heavensward Minstrel's Ballads and that's where I personally noticed it.

**Comment by MidoriKami** [comment]
closed with ea6ac611c62e193717f39fc13cc8a3dbb91ddc40
