### ISSUE TITLE
More basic instinct edge cases

### ISSUE THREAD

**Issue by quisquous** [MidoriKami/NoTankYou#39]
(I am on v5.0.3.7, which I assume has the fix from #37.)

I think "bound by duty" is not fully the answer.  You can be in the overworld and do a battle leve which makes you bound by duty, but basic instinct can't be used there because you're still in the overworld.  Also, carnivale is a solo instance where you are bound by duty but basic instinct can't be used there because it's not content meant for more than two people.

Maybe a blacklist of territory ids?  (I could give you a list if that'd be helpful.)  Or do a more dynamic territory id -> content finder condition / content type lookup from game data to only show basic instinct in territories for party content?

**Comment by MidoriKami** [comment]
Either I remove the basic instinct feature entirely or I leave it as it currently is.

I am not adding special levequest handling.

**Comment by MidoriKami** [comment]
I might revisit this later but blue is extremely annoying to deal with. 

I'm not adding anything that requires being updated for a patch to continue working correctly. A cfc lookup for a particular battalion type might work but I am not going to spend the time on that right now I have other projects I'd rather work on.

A PR would be potentially accepted.
