### ISSUE TITLE
NoTankYou causing hard Crash to Desktop when Loading into game or changing maps/areas

### ISSUE THREAD

**Issue by Aceman67** [MidoriKami/NoTankYou#4]
While having NoTankYou active in my addon list, loading into the game from the Queue or changing maps causes an instant Crash to Desktop.

Here is the link to the Discord post I put up with my Logfile: [https://discord.com/channels/581875019861328007/584827243617058816/918431877503791134](url)

Removing the addon stopped the crashes. I'm not technical enough to know the exact cause. Hope this helps

[dalamud.log](https://github.com/MidoriKami/NoTankYou/files/7690010/dalamud.log)

~Fluttershy Flutters

**Comment by MidoriKami** [comment]
Delete your config file in 
%appdata%\Roaming\XIVLauncher\pluginConfigs\NoTankYou.json

**Comment by MidoriKami** [comment]
I just released an update to Dalamud that will forcefully reset any outdated configuration files.
It also auto-disables in PvP now.
