### ISSUE TITLE
Zone filters for food warning not working for Criterion (normal)

### ISSUE THREAD

**Issue by DenL** [MidoriKami/NoTankYou#40]
I have my zone filter setup as such:
![image](https://user-images.githubusercontent.com/5632219/205460462-f3e88b7e-1721-4870-9e4d-34cf2dfa01c6.png)

Food warning does not show up at all unless I disable the zone filter. This is in normal Criterion; have not tested in savage since I have not unlocked it.

**Comment by MidoriKami** [comment]
Attach a copy of your dalamud log
