### ISSUE TITLE
Chocobo warning bug

### ISSUE THREAD

**Issue by jtoya85** [MidoriKami/NoTankYou#43]
First off, I mentioned this in the help forum for NoTankYou on the Dalamud discord server but it seems no one acknowledged it. I was doing a 4-person duty yesterday June 26th and as soon as the final boss was defeated and the cutscene was finished the Chocobo warning popped up. I hadn't left the duty yet but as soon as I did, and into a sanctuary, the warning disappeared. Today as soon as I loaded into World of Darkness the warning popped up immediately but disappeared once the alliance was able to start. I'm not sure if there is a setting that I toggled that I shouldn't have but as far as I can tell the Chocobo module is setup the same, or similarly, to the other 7 modules I have enabled, with the only exception being I have the Chocobo warning set to 4th priority.

**Comment by MidoriKami** [comment]
What plugin version?

**Comment by jtoya85** [comment]
5.1.3.3

**Comment by MidoriKami** [comment]
v6.0.0.0 is currently in testing. Bugs or issues for older versions are no longer relevant.
