### ISSUE TITLE
Possibility for Dance Partner, Fairy, Kardia etc?

### ISSUE THREAD

**Issue by byu46** [MidoriKami/NoTankYou#5]
There are a couple other "set and forget but forgettable to set" skills in the game like the skills in the title! Would it be possible to extend the behaviour of No Tank You for these? If it's not too hard I can do it myself in a pull request and also learn a bit about making ff plugins :D but I wasn't sure if you wanted to keep this plugin locked to tank stance :0

**Comment by MidoriKami** [comment]
If you are interested in making plugins, join the goat place discord you can find all kinds of resources there for developing FFXIV plugins. https://discord.gg/3NMcUV5

I will not be adding the above features to "NoTankYou" as it is intended purely for tanks. _I mean, it's in the awesome name right?_

I am however developing a second addon to do some of the features you noted here. It's name will be "PartnerUp"
