### ISSUE TITLE
Scaling issues

### ISSUE THREAD

**Issue by AngelSeed** [MidoriKami/NoTankYou#50]
https://gyazo.com/77c5351d3065a2a0fe89bb4d63a38274
https://gyazo.com/8ae9ee8a666fb6f64333b2c5acddb71c
My resolution does not work properly like this, but is there any countermeasure?
It worked fine in previous versions, but
Since the new version, texts and banners have disappeared.

**Comment by AngelSeed** [comment]
Disabling all other plugins didn't fix the problem.

**Comment by MidoriKami** [comment]
![image](https://github.com/MidoriKami/NoTankYou/assets/9083275/c9a7722a-975c-4151-a837-864744c4facc)
Works fine for me? I need more information. Please provide any context you think might be useful.

**Comment by fzurita** [comment]
I also stopped seeing any sort of alerts in recent versions. This was working fine. I do have a 4k monitor and I have scaling set to 150 in the game system configuration.

**Comment by MidoriKami** [comment]
Please zip up your NoTankYou config folder and post it here (both of you)

**Comment by fzurita** [comment]
Here you go:

[NoTankYou.zip](https://github.com/MidoriKami/NoTankYou/files/11994194/NoTankYou.zip)

**Comment by fzurita** [comment]
I tried deleting all configuration while the plugin was disabled and then I re-enabled the plugin. Nothing shows still. Even in "Preview mode".

**Comment by MidoriKami** [comment]
Send Dalamud.log after attempting to generate a warning ingame

**Comment by fzurita** [comment]
I just tried to generate a warning for scholar:
[dalamud.log](https://github.com/MidoriKami/NoTankYou/files/11994335/dalamud.log)

I'm in a sanctuary but I don't have the setting enable to hide in sanctuary.

**Comment by fzurita** [comment]
I don't see any logs for NoTankYou in that log file even though I can see in the logs that it was loaded.

**Comment by MidoriKami** [comment]
I don't see any errors in the log, so I genuinely have nothing to work with.

Only thing I can suggest is relaunch the game without unsupported plugins
![image](https://github.com/MidoriKami/NoTankYou/assets/9083275/2446ffb3-5d6c-4a37-ad13-4486b9e42d6c)

**Comment by fzurita** [comment]
That did not seem to help.

**Comment by fzurita** [comment]
I started the game with only No Tank You enabled and I still can't see anything.

**Comment by fzurita** [comment]
Ok, I figured out what is causing the issue.

It works fine in full screen mode, it doesn't work in "Borderless WIndowed" mode. It used to work before.

**Comment by MidoriKami** [comment]
![image](https://github.com/MidoriKami/NoTankYou/assets/9083275/e688b7a6-9237-4788-87e5-89df345c5bfe)

🤔

**Comment by fzurita** [comment]
Ok, even more clues. It works fine "Borderless Window" mode, as long as I disable the Dalamud Setting "Enable multi-monitor windows" under "Look and Feel".

**Comment by MidoriKami** [comment]
Ahhhh, now we are at the root. Alright I know how to fix that.

**Comment by MidoriKami** [comment]
https://github.com/MidoriKami/NoTankYou/assets/9083275/a4876a3b-6981-4393-86be-03d887c601fb

It's using absolute screen coordinates instead of relative coordinates.

**Comment by fzurita** [comment]
LOL

**Comment by AngelSeed** [comment]
Sorry for being late.
[NoTankYou.zip](https://github.com/MidoriKami/NoTankYou/files/11995680/NoTankYou.zip)

**Comment by AngelSeed** [comment]
It is solved.
Thank you for solving it by turning off Dalamud's multi-monitor window.
