### ISSUE TITLE
Flickering text in Party List

### ISSUE THREAD

**Issue by Glyceri** [MidoriKami/NoTankYou#55]
Hi 👋
You're updating ATK text on [Framework Update](https://github.com/MidoriKami/NoTankYou/blob/master/NoTankYou/System/NoTankYouSystem.cs#L106) instead of hooking into the elements own Update or Draw function which causes flicker to occur.
![NTYbug-ezgif com-video-to-gif-converter (1)](https://github.com/MidoriKami/NoTankYou/assets/78602618/74384650-a38c-48a0-9196-8821710d86b0)

**Comment by Glyceri** [comment]
Ahh yeah true, hooking into Update does the trick

**Comment by MidoriKami** [comment]
Nah just subscribe to AddonPostDraw and AddonPostRequestedUpdate.
