### ISSUE TITLE
Bug in 6.0.2.2: Job icons not visible after stance was turned on

### ISSUE THREAD

**Issue by RationalSquash** [MidoriKami/NoTankYou#56]
![image](https://github.com/MidoriKami/NoTankYou/assets/35276739/76cffbd6-cea7-4973-8203-bde132ef58a0)

Got the update for 6.0.2.2 today, and seems like something broke. Icons for tanks disappeared when one turned on stance.
This was in "The Howling Eye (Hard)"

It was blinking like normal when neither had it on, but afterwards they were gone and did not come back. 
![image](https://github.com/MidoriKami/NoTankYou/assets/35276739/5a639cae-c62c-452a-9e8f-3777119f51e8)
![image](https://github.com/MidoriKami/NoTankYou/assets/35276739/5dc1166b-9e3c-4984-9ea1-281359647006)
![image](https://github.com/MidoriKami/NoTankYou/assets/35276739/cf06aca4-01e6-4301-85e1-b10a2c567642)

I disabled notankyou, and they came back. Reenabling it didn't remove them after.

It only happened in this one instance (so far).

**Comment by MidoriKami** [comment]
This is a known one-off bug that happens when updating. It'll fix itself eventually.

**Comment by RationalSquash** [comment]
Doesn't seem like its a one-off. Its happened in every trial and raid i've been in since (>10). I have restarted both the game and pc, the issue is still there.

![image](https://github.com/MidoriKami/NoTankYou/assets/35276739/30849b2a-7ac3-4918-b03e-7f87fd03a14e)
![image](https://github.com/MidoriKami/NoTankYou/assets/35276739/89838e61-0ae8-44fd-8c5d-7471c3dde308)

If this is still normal behaviour, do you have an estimate for "eventually"?

**Comment by RationalSquash** [comment]
From testing i've been able to narrow it down to it happening if the warning goes away during the time the shield icon is showing. It is reproducable on command. It happens for any warning "reason". The ones in the screenshots above where the whole party goes blank is because of the food warning going away as the boss is pulled.

I have talked to others that are experiencing the exact same issue. Are you sure the change to warning display logic in the newest release is not the cause of this? For now i'll just turn off the job icon warning in the settings until this is fixed.
