### ISSUE TITLE
Custom nodes in party list have collision

### ISSUE THREAD

**Issue by sersorrel** [MidoriKami/NoTankYou#60]
As the title says – the nodes NTY adds to the party list have collision/intercept clicks.

The easiest way to see this is to click on a job icon in the party list; it should select that player, but with NTY loaded, it doesn't.

This also impacts the empty space below the party list (where job icons would be) when the party isn't full.

**Comment by MidoriKami** [comment]
Thanks that's a bug in KamiToolKit, I was accidentally setting event flags for all nodes, it's been fixed internally for a couple days, should fix itself with the next update.
