### ISSUE TITLE
No Modules showing

### ISSUE THREAD

**Issue by ParallelSigns** [MidoriKami/NoTankYou#66]
Hello.

I don't seem to have any modules showing like in the previews for NTW. Instead, mine is just blank like so:

![image](https://github.com/user-attachments/assets/949c9623-9f13-4dec-b764-aa968e5786ba)

I'm unsure what could be causing this, or if anyone else is having such an issue.

**Comment by MidoriKami** [comment]
Please upload dalamud.log here

**Comment by ParallelSigns** [comment]
Is there somewhere private/safe I'd be able to upload it for you? It's got my name because of the filepath to appdata. (Or if I remove mentions of my name from the log, would that be workable for you without it making your life more difficult?)

Thanks

**Comment by ParallelSigns** [comment]
> Please upload dalamud.log here

[dalamud.log](https://github.com/user-attachments/files/16592823/dalamud.log)

**Comment by MidoriKami** [comment]
![image](https://github.com/user-attachments/assets/6e8c8745-192a-44d6-ac89-fbc9fc7307b7)

**Comment by ParallelSigns** [comment]
> ![image](https://private-user-images.githubusercontent.com/9083275/357493238-6e8c8745-192a-44d6-ac89-fbc9fc7307b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NzMwMzcsIm5iZiI6MTcyMzU3MjczNywicGF0aCI6Ii85MDgzMjc1LzM1NzQ5MzIzOC02ZThjODc0NS0xOTJhLTQ0ZDYtYWM4OS1mYmM5ZmM3MzA3YjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTNUMTgxMjE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWYyYjkwNjhjMDA5MDZlZjNkZmEyNjRiZTcwNTM1NTJmNjM3MGQ2OGRhMTk2MzlmMTdmZGUwNDk0YTFkNjYzMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0Pt3-uBYrfdG6Ek_W_49dS0fLHRERRdiIEv36WLKUak)

Hello again. I've just tried what you suggested and there has been zero change for me. I still have nothing appearing in the Modules section. Sorry. :(

**Comment by MidoriKami** [comment]
Seek help in the discord.
