### ISSUE TITLE
Unable to load: Requiring WQHD/4k resolution

### ISSUE THREAD

**Issue by abandon-the-flesh** [MidoriKami/NoTankYou#67]
The plugin failed to load. Please contact the author for more information.
![image](https://github.com/user-attachments/assets/401d9d63-970b-4c6a-90d1-29deb8c6c282)

**Comment by MidoriKami** [comment]
Requires this setting in the System Configuration option to be set.

![image](https://github.com/user-attachments/assets/b10dab54-b1c7-4998-977f-e54b530eb749)

**Comment by abandon-the-flesh** [comment]
ok thank you, i dont have this supported resolution and thought it would mess up my hotbars. i appreciate the update.
