### ISSUE TITLE
Plugin requires "UI Resolution" System Configuration setting to be set to High (WQHD/4K)

### ISSUE THREAD

**Issue by Counterpoint-Storm** [MidoriKami/NoTankYou#68]
I'm not sure if this was intended or not, but when updating to the latest version of NTY when prompted, this error occurred. The simple fix seems to be just doing what it asks, but my game is currently running on default settings, and this seems like an odd choice.

![NTY UI 4K](https://github.com/user-attachments/assets/cb9ac0ba-4e76-458a-a0c0-3e94ab6073f7)

**Comment by MidoriKami** [comment]
Duplicate #67
