### ISSUE TITLE
Unable to load version Version 7.0.2.3

### ISSUE THREAD

**Issue by Dididada1212** [MidoriKami/NoTankYou#69]
after I upgraded to the latest version I keep getting this error when the plugin tries to load

"Error
NoTankyou (unloaded)
Plugin requires "UI Resolution" System Configuration setting to be set to "High (WQHD/4K)"
"
I run on 1080 and I cant go higher than that.

**Comment by MidoriKami** [comment]
You're not understanding what setting is being asked for please read the pinned issue https://github.com/MidoriKami/NoTankYou/issues/67
