### ISSUE TITLE
Order issue in party list

### ISSUE THREAD

**Issue by Aireil** [MidoriKami/NoTankYou#72]
Issue with the party order from the HUD agent, should use the index.
https://cdn.discordapp.com/attachments/934817829931319327/1307315899883065384/2024-11-16_13-05-57.mp4?ex=6739dc4f&is=67388acf&hm=2e1919db343c7ebf0e86a17a842ee85e83811f590d00feaa4ebe87f11bd7dbde&

**Comment by MidoriKami** [comment]
Potentially fixed in adce00ede89e5fd49c8f2ca1c2e625360429b5a5 , waiting on confirmation to close issue.

**Comment by MidoriKami** [comment]
Assuming this is fixed with the latest release, if it isn't please reopen.
