### ISSUE TITLE
Zone Filter not being applied during Treasure Maps

### ISSUE THREAD

**Issue by ScrachC** [MidoriKami/NoTankYou#73]
With the Beta, currently I believe the zone filter is not working properly. When doing Dawntrail Treasure Maps (didn't do other expansion ones), the Food Buff warning gets triggered when you open the initial chest with the add waves, even though I have the 4 standard options enabled for Zone Filter. It doesn't happen though in the zone _Cenote Ja Ja Gural_ or just in the Overworld attacking standard mobs.

**Comment by MidoriKami** [comment]
Likely fixed via c9c4f371625cad14258dc611a8ea490da58100d9, though I have not released an update to NoTankYou with the fix applied.

Once the next update is released, please confirm if that fixes this issue.

**Comment by MidoriKami** [comment]
Assuming this is fixed with latest release if it isn't please reopen.
