### ISSUE TITLE
NTY pop-ups and ui-elements appear in PVP arenas/zones

### ISSUE THREAD

**Issue by Alluneve** [MidoriKami/NoTankYou#74]
Did pvp on scholar, 

the reminder was there to summon eos, it shouldn't be there in that specific.

![afbeelding](https://github.com/user-attachments/assets/00802fbc-d6a4-48f4-b045-ab18f211be23)

**Comment by Aireil** [comment]
I think that's a quite weird thing to say won't fix on, it should definitely be excluded by default for PvP regardless of the blacklist feature.
Especially with how easy it is to just use IsPvp.

**Comment by Alluneve** [comment]
![afbeelding](https://github.com/user-attachments/assets/39652245-7ee2-4e51-aac8-4dc2213b99f4)
not all anti-pvp checks were removed.

WindowManager still disables the config window when clientstate.ispvp in kamilib

if we're going ALL-in on the zone blacklister, maybe on initial file creation, pre-add zones: 250 wolves den pier, 1116 clockwork castletown, 1032 the palaistra, 1138 the red sands, 376 Borderlands ruin secure, 431 Seal rock, 554 The fields of glory, 888 onsal hakair, 791 hidden gorge and 729 astragalos as a default-existing blacklist?

**Comment by MidoriKami** [comment]
I'm not against having a pvp check inside certain modules, but as I know absolutely nothing about pvp as it's a game mode I intentionally avoid and have no interest in, I have no idea which modules would need it.

A PR to add pvp checks to individual modules would be welcome.

I'll update KamiLib to remove the PvP checks, I thought I did already, must have forgotten.
