### ISSUE TITLE
Food Warning shows in overworld

### ISSUE THREAD

**Issue by StellarJay77** [MidoriKami/NoTankYou#76]
Please reproduce issue with latest version, I recently released an update.

If the issue persists reopen this issue.

_Originally posted by @MidoriKami in https://github.com/MidoriKami/NoTankYou/issues/75#issuecomment-2487019641_

**Comment by StellarJay77** [comment]
Issue still happens as of today in the overworld when doing maps, as soon as map is opened before combat and after combat before entering portal or before opening chest.

![image](https://github.com/user-attachments/assets/08ee8e57-d731-4378-9f77-dbb157e8053e)

**Comment by MidoriKami** [comment]
Check `/xldata condition` ingame, I believe it will show `BoundByDuty` when a treasure map event is active. Can you attach a screenshot of the `/xldata condition` window after starting a treasure map event?

**Comment by StellarJay77** [comment]
![image](https://github.com/user-attachments/assets/f6cbf8b6-bbb7-47f3-947d-60955f74d814)

**Comment by StellarJay77** [comment]
Last image was after first mob kill and food warnings were showing. This was after we completed killing overworld mobs and chest was open with no portal spawn. 
![image](https://github.com/user-attachments/assets/6ffdaea7-97b2-46e6-bdb4-4adae5a3f0ef)

**Comment by MidoriKami** [comment]
So in that case, the NoTankYou is behaving correctly. I recommend using the filters in the food module to only show in Extremes/Unreal/Ultaimte/Savage duties.

Alternatively, you can blacklist the overworld zones using the blacklist feature to disable all warnings while in those zones.

**Comment by MidoriKami** [comment]
It's an unfortunate consequence of how square enix programmed the game and how these events work.

**Comment by StellarJay77** [comment]
I do have it checked so that it should only show in Extreme/Unreal/Ult/Savage. It used to work fine.

**Comment by MidoriKami** [comment]
Ah well that's a different problem, I'll look into it.

**Comment by StellarJay77** [comment]
![image](https://github.com/user-attachments/assets/e2821ef4-d6aa-4507-a198-d9cbcacd4193)

**Comment by StellarJay77** [comment]
> Ah well that's a different problem, I'll look into it.

Thank you for taking the time to look into this. I know it's just a minor annoyance but being a dev myself I know sometimes minor annoyance bugs can cause bigger issues down the road if not addressed. You're probably right though that it's something SE did to trim down some of the spaghetti code bloat.
