### ISSUE TITLE
Add notification for dead party member

### ISSUE THREAD

**Issue by Deadscale** [MidoriKami/NoTankYou#8]
Howdy,

Not sure if this is a good place for suggestions, I was wondering if a notification for a dead party member would be possible.

When playing a DPS class that can raise like Summoner or RDM I tend to not be paying attention to the party list, having a pop-up saying "someone's dead" would be handy.

**Comment by MidoriKami** [comment]
This functionality is present in a different plugin by the name of ["RezPls"](https://github.com/Ottermandias/RezPls)
I will not be integrating the core features of other plugins into mine.
