### ISSUE TITLE
Suggestion: Buff Food Warning

### ISSUE THREAD

**Issue by Ergwano** [MidoriKami/NoTankYou#9]

**Comment by Ergwano** [comment]
A notification when your Buff Food runs out or is running out shortly.
I think it would fit into the other kind of warnings of this Plugin
(Sorry accidently submitted this empty)

**Comment by MidoriKami** [comment]
This plugin is intended to be a "hey xyz do your combat related thing" at the beginning of dungeons. There's another plugin that is a work in progress by another developer to create reminders for everything else.

**Comment by MidoriKami** [comment]
Well this aged poorly. Haha.
